name: grafana
image: mcp/grafana
type: server
meta:
  category: monitoring
  tags:
    - grafana
    - monitoring
about:
  title: Grafana
  icon: https://avatars.githubusercontent.com/u/7195757?s=200&v=4
source:
  project: https://github.com/grafana/mcp-grafana
  branch: main
  commit: 1933b888202fff69f11f420572a13da3e9fa93ee
run:
  command:
    - --transport=stdio
config:
  description: Configure the connection to Grafana
  secrets:
    - name: grafana.api_key
      env: GRAFANA_API_KEY
      example: <your service account token>
  env:
    - name: GRAFANA_URL
      example: http://localhost:3000
      value: "{{grafana.url}}"
  parameters:
    type: object
    properties:
      url:
        type: string
