name: grafana
image: dhi.io/grafana-mcp
type: server
meta:
  category: monitoring
  tags:
    - grafana
    - monitoring
about:
  title: Grafana
  icon: https://avatars.githubusercontent.com/u/7195757?s=200&v=4
source:
  project: https://github.com/docker-hardened-images/catalog
  commit: 51238303911efa37052fae6860411fe20475880c
  branch: main
  dockerfile: image/grafana-mcp/debian/0.yaml
run:
  command:
    - --transport=stdio
config:
  description: Configure the connection to Grafana
  secrets:
    - name: grafana.api_key
      env: GRAFANA_API_KEY
      example: <your service account token>
  env:
    - name: GRAFANA_URL
      example: http://localhost:3000
      value: "{{grafana.url}}"
  parameters:
    type: object
    properties:
      url:
        type: string
